#destination: "~/Development/Hispanics/_site"
title: Hispanics in Computing
email: maperezquinones@gmail.com
description: Hispanics in Computing

# For deployment
#baseurl: "/hispanicsincomputing"
baseurl: ""

# The base hostname & protocol for your site
# url: "https://hispanicsincomputing.org" 
url: "https://mapq.github.io/hispanicsincomputing/" 

exclude: ["documentation", "bin"]
